SELECT
 EXTRACT (DATE
 FROM
   creation_time) AS EXECUTION_DATE,
 COUNT(*) TOTAL_QUERIES,
 SUM(total_slot_ms/TIMESTAMP_DIFF(end_time, creation_time, MILLISECOND)) SUM_SLOT_USAGE,
 AVG(total_slot_ms/TIMESTAMP_DIFF(end_time, creation_time, MILLISECOND)) AVG_SLOT_USAGE,
 MIN(total_slot_ms/TIMESTAMP_DIFF(end_time, creation_time, MILLISECOND)) MIN_SLOT_USAGE,
 MAX(total_slot_ms/TIMESTAMP_DIFF(end_time, creation_time, MILLISECOND)) MAX_SLOT_USAGE,
 SUM(TIMESTAMP_DIFF(end_time, creation_time, SECOND)) TOTAL_DURATION_IN_SECONDS,
 AVG(TIMESTAMP_DIFF(end_time, creation_time, SECOND)) AVG_DURATION_IN_SECONDS,
 SUM(total_bytes_processed*1e-12) TOTAL_PROCESSED_TB
FROM
`region-us.INFORMATION_SCHEMA.JOBS_BY_PROJECT`
WHERE
 state = 'DONE'
 AND statement_type = 'SELECT'
 AND creation_time BETWEEN TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
 AND CURRENT_TIMESTAMP()
GROUP BY
 EXECUTION_DATE
ORDER BY
 EXECUTION_DATE,
 SUM_SLOT_USAGE DESC
